#!/bin/bash
# ============================================================
# Confound regression with fsl_regfilt
# Generated by fMRI Denoiser app — 2026-04-24 13:19
# ============================================================
#
# Derivatives : //data03/MRI_hackaton_data/Data_collection/fmriprep_synthstrip_NO_CSF
# Tasks       : rest
# Subjects    : 7
#
# Confound files used (pre-built by the app):
#   _desc-confounds_timeseries.tsv
#
# Selected regressors (3 total):
#   a_comp_cor_02 a_comp_cor_04 a_comp_cor_06
#
# NOTE: Confound .txt files were pre-built by the app.
# Re-run the app if you want to change the confound selection.
#
# To run:
#   nohup bash run_regfilt.sh > run_regfilt.log 2>&1 &
# ============================================================

deriv_dir="//data03/MRI_hackaton_data/Data_collection/fmriprep_synthstrip_NO_CSF"
n_parallel=5

# ── Per-subject processing ─────────────────────────────────────────────────
process_subject() {
    local sub="$1"
    echo "=== ${sub}: started ==="

    for bold in $(find "${deriv_dir}/${sub}" -name "*_desc-preproc_bold.nii.gz" | sort); do

        # Keep only selected tasks (all runs included automatically)
        [[ "${bold}" != *"_task-rest_"* ]] && continue

        local confounds="${bold/_desc-preproc_bold.nii.gz/_desc-selected_confounds.txt}"
        local output="${bold/_desc-preproc_bold.nii.gz/_desc-denoised_bold.nii.gz}"
        local n_cols=$(awk "NR==1{print NF}" "${confounds}")
        local indices=$(seq 1 ${n_cols} | paste -sd,)

        echo "  ${sub}: $(basename ${bold})"
        fsl_regfilt \
            -i "${bold}" \
            -d "${confounds}" \
            -f "${indices}" \
            -o "${output}"
    done

    echo "=== ${sub}: done ==="
}
export -f process_subject
export deriv_dir

# ── Subjects to process ────────────────────────────────────────────────────
subjects=(
    "sub-gutsaumc0010"
    "sub-gutsaumc0011"
    "sub-gutsaumc0012"
    "sub-gutsaumc0014"
    "sub-gutsaumc0015"
    "sub-gutsaumc0016"
    "sub-gutsaumc0017"
)

printf '%s\n' "${subjects[@]}" | xargs -n1 -P${n_parallel} -I{} bash -c 'process_subject {}'
